# Generated by Django 2.2.2 on 2020-02-12 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treeHealth', '0002_auto_20200130_1449'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserHistoryView',
        ),
    ]
