# Generated by Django 2.2.2 on 2020-01-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeHealth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthResults',
            fields=[
                ('health_results_id', models.AutoField(db_column='id_health_results', primary_key=True, serialize=False)),
                ('height', models.FloatField(blank=True, db_column='height', null=True)),
                ('biomass', models.FloatField(blank=True, db_column='biomass', null=True)),
                ('carbon_content', models.FloatField(blank=True, db_column='carbon_content', null=True)),
                ('total_carbon_absorbed', models.FloatField(blank=True, db_column='total_carbon_absorbed', null=True)),
            ],
            options={
                'db_table': 'health_results',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserHistoryView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_column='id_user')),
                ('android_id', models.CharField(db_column='android_id', max_length=100)),
                ('image', models.ImageField(db_column='image', upload_to='')),
            ],
            options={
                'db_table': 'user_history_view',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UserMobile',
        ),
    ]
